"""enable cascade delete for chunks

Revision ID: e3c1d746f0c4
Revises: e5de58d8126c
Create Date: 2025-11-19 11:48:43.127325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c1d746f0c4'
down_revision: Union[str, Sequence[str], None] = 'e5de58d8126c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add ON DELETE CASCADE to chunks foreign key."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ลบ Foreign Key เก่าที่ไม่มี ON DELETE CASCADE
    op.drop_constraint('chunks_document_id_fkey', 'chunks', type_='foreignkey')
    
    # 2. สร้าง Foreign Key ใหม่ พร้อมเงื่อนไข ON DELETE CASCADE
    op.create_foreign_key(
        'chunks_document_id_fkey',  # ชื่อ Constraint (ควรใช้ชื่อเดิม)
        'chunks',                   # ตารางลูก
        'documents',                # ตารางแม่
        ['document_id'],            # คอลัมน์ในตารางลูก
        ['id'],                     # คอลัมน์ในตารางแม่
        ondelete='CASCADE'          # <-- แก้ไขตรงนี้!
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Remove ON DELETE CASCADE."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ลบ Foreign Key เก่าที่มี ON DELETE CASCADE
    op.drop_constraint('chunks_document_id_fkey', 'chunks', type_='foreignkey')
    
    # 2. สร้าง Foreign Key ใหม่ (กลับไปใช้แบบเดิมที่ไม่มี ON DELETE CASCADE)
    op.create_foreign_key(
        'chunks_document_id_fkey',
        'chunks',
        'documents',
        ['document_id'],
        ['id']
        # ไม่ใส่ ondelete='CASCADE'
    )
    # ### end Alembic commands ###